export const levels = [
  {
    "id": "60f3bd98006a9337008b3376",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1626586520810,
    "uploaded": 1626586520810,
    "votes": 1,
    "course": {
      "version": 2,
      "header": {
        "modified": 1623357480,
        "title": "CLOUDPUFF CIRCUIT/THORNSTAR TEST",
        "description": "(RED COIN 1 AREA) CLOUDYPUFF- EASY, SAFE RACE THORNSTAR-HARD, PERILOUS TEST",
        "start_y": 2,
        "finish_y": 7,
        "finish_x": 2305,
        "time": 500,
        "game_style": "MW",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 59116,
        "game_version": 32,
        "management_flags": 67,
        "creation_id": 591617313,
        "upload_id": 30934314,
        "completion_version": 5
      },
      "course_area": {
        "course_theme": "SKY",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 1122,
        "sound_effect_count": 56,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 2252,
        "track_count": 95,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "FOREST",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 1,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 1,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "NIGHT",
        "object_count": 1615,
        "sound_effect_count": 14,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 1820,
        "track_count": 104,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "609a8c6e0056bf6a008b1a90",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1620741230518,
    "uploaded": 1620741230518,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1584609900,
        "title": "伝説勇者の試練　Test of Legendary Hero",
        "description": "謎解き要素もあり、楽しさは倍に。この試練をクリアして、リンクを巧みに使いこなそう。　リンクだからこそできることは無限大。※再投稿",
        "start_y": 2,
        "finish_y": 3,
        "finish_x": 1085,
        "time": 400,
        "game_style": "M1",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 120003,
        "game_version": 13,
        "management_flags": 67,
        "creation_id": 510204957,
        "upload_id": 15781678,
        "completion_version": 3
      },
      "course_area": {
        "course_theme": "UNDERGROUND",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 1888,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 401,
        "sound_effect_count": 42,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 1899,
        "track_count": 8,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "UNDERGROUND",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 407,
        "sound_effect_count": 2,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 3744,
        "track_count": 28,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "609a1a7200b132c800095139",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1620712050924,
    "uploaded": 1620712050924,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1564254540,
        "title": "A Fight to Fall the Fastest",
        "description": "A race down the clouds for multiplayer versus mode.",
        "start_y": 4,
        "finish_y": 10,
        "finish_x": 1565,
        "time": 300,
        "game_style": "MW",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 58983,
        "game_version": 2,
        "management_flags": 67,
        "creation_id": 2946378703,
        "upload_id": 6989686,
        "completion_version": 1
      },
      "course_area": {
        "course_theme": "SKY",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 2656,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 115,
        "sound_effect_count": 0,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 2972,
        "track_count": 0,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "SKY",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "VERTICAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 768,
        "top_boundary": 2688,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 628,
        "sound_effect_count": 0,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 3268,
        "track_count": 32,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "609a192c001d044700095019",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1620711724291,
    "uploaded": 1620711724291,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1607279460,
        "title": "The Trust Test™",
        "description": "You can trust me :) - Follow the arrows! Aren't I a helpful game designer?",
        "start_y": 14,
        "finish_y": 14,
        "finish_x": 705,
        "time": 300,
        "game_style": "M1",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 23665,
        "game_version": 32,
        "management_flags": 67,
        "creation_id": 2750731935,
        "upload_id": 26638193,
        "completion_version": 5
      },
      "course_area": {
        "course_theme": "SNOW",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 1280,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 84,
        "sound_effect_count": 10,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 785,
        "track_count": 4,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "SNOW",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "VERTICAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 768,
        "top_boundary": 672,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 5,
        "sound_effect_count": 0,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 4,
        "track_count": 0,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "5f02cfe00081c6e800261366",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1594019808786,
    "uploaded": 1594019808786,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1591194360,
        "title": "Mario Maker Math Test!!likes ",
        "description": "Mis estudiantes: Roberto9, Vaña , Dany river. Se enfrentaran a mi examen :)",
        "start_y": 3,
        "finish_y": 3,
        "finish_x": 2305,
        "time": 500,
        "game_style": "W3",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 23241,
        "game_version": 16,
        "management_flags": 67,
        "creation_id": 1078508138,
        "upload_id": 20306301,
        "completion_version": 4
      },
      "course_area": {
        "course_theme": "SNOW",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 1,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 1,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 744,
        "sound_effect_count": 36,
        "snake_block_count": 0,
        "clear_pipe_count": 10,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 2810,
        "track_count": 0,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "SNOW",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 1,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 1,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 304,
        "sound_effect_count": 26,
        "snake_block_count": 0,
        "clear_pipe_count": 6,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 1308,
        "track_count": 0,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "5ed94f9900ba25cf00223ef4",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1591299992842,
    "uploaded": 1591299992842,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1584609900,
        "title": "伝説勇者の試練　Test of Legendary Hero！",
        "description": "謎解き要素もあり、楽しさは倍に。この試練をクリアして、リンクを巧みに使いこなそう。　リンクだからこそできることは無限大。※再投稿,　<final>",
        "start_y": 2,
        "finish_y": 3,
        "finish_x": 1085,
        "time": 400,
        "game_style": "M1",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 120003,
        "game_version": 13,
        "management_flags": 67,
        "creation_id": 510204957,
        "upload_id": 15781678,
        "completion_version": 3
      },
      "course_area": {
        "course_theme": "UNDERGROUND",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 1888,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 401,
        "sound_effect_count": 42,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 1899,
        "track_count": 8,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "UNDERGROUND",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 3840,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 407,
        "sound_effect_count": 2,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 3744,
        "track_count": 28,
        "icicle_count": 0
      }
    }
  },
  {
    "id": "5dc426d8000c8cad00ceb027",
    "owner": "5972237ef160681a439d97ba",
    "uploader": "Tarnadas",
    "difficulty": "easy",
    "lastModified": 1573136088234,
    "uploaded": 1573136088234,
    "votes": 0,
    "course": {
      "version": 2,
      "header": {
        "modified": 1562352180,
        "title": "Super Guitario Bros.test",
        "description": "Warm up with a quick tutorial, and then choose from 3 different songs!",
        "start_y": 5,
        "finish_y": 1,
        "finish_x": 1465,
        "time": 500,
        "game_style": "M1",
        "clear_condition_type": "NONE",
        "clear_condition": 0,
        "clear_condition_amount": 0,
        "clear_check_tries": 1,
        "clear_check_time": 55116,
        "game_version": 2,
        "management_flags": 67,
        "creation_id": 3099586904,
        "upload_id": 4529437,
        "completion_version": 1
      },
      "course_area": {
        "course_theme": "GHOUST_HOUSE",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 2496,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 733,
        "sound_effect_count": 14,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 1027,
        "track_count": 375,
        "icicle_count": 0
      },
      "course_sub_area": {
        "course_theme": "CASTLE",
        "auto_scroll": "NONE",
        "screen_boundary": "ABOVE_LINE",
        "orientation": "HORIZONTAL",
        "liquid_max": 0,
        "liquid_mode": "FIXED",
        "liquid_speed": "NONE",
        "liquid_min": 0,
        "right_boundary": 2112,
        "top_boundary": 432,
        "left_boundary": 0,
        "bottom_boundary": 0,
        "day_time": "DAY",
        "object_count": 562,
        "sound_effect_count": 0,
        "snake_block_count": 0,
        "clear_pipe_count": 0,
        "piranha_creeper_count": 0,
        "exclamation_block_count": 0,
        "track_block_count": 0,
        "tile_count": 505,
        "track_count": 204,
        "icicle_count": 0
      }
    }
  }
]